### ISSUE TITLE
Repeated usage of h_mlp in Local_MP

### ISSUE THREAD

**Issue by PiotrKaszuba** [zetayue/MXMNet#10]
It seems to me that Cross Layer Mapping (Gg -> Gl) is overwritten and used twice, instead of the part of the update function. Is that intended or should lines 84 and 124 use self.mlp, instead of self.h_mlp, similarly to Global_MP?

https://github.com/zetayue/MXMNet/blob/fa1dbc5153d48b7380c9f20da21390e2a5aee8e5/layers.py#L66
https://github.com/zetayue/MXMNet/blob/fa1dbc5153d48b7380c9f20da21390e2a5aee8e5/layers.py#L84
https://github.com/zetayue/MXMNet/blob/fa1dbc5153d48b7380c9f20da21390e2a5aee8e5/layers.py#L93
https://github.com/zetayue/MXMNet/blob/fa1dbc5153d48b7380c9f20da21390e2a5aee8e5/layers.py#L124

**Comment by zetayue** [comment]
Thank you for your interest in our project and for reporting the issue! Upon further investigation, I found that the repeated usage of `h_mlp` was a mistake on my part while refactoring the code before uploading it on GitHub. The raw code for conducting the experiments does not have this issue. I have already fixed the issue with a new commit. Please feel free to continue providing feedback and reporting any issues you may find in my repo.

**Comment by PiotrKaszuba** [comment]
Thank you for the time you took to clarify the issue and update the code!
